feat: add setting options for execution environment
ansible/vscode-ansible pull request #200
Opened 2021-09-27 05:28 UTC by ganeshrn

*  Add setting in package.json file to configure execution
   environment related setting.
   Example client `settings.json` for EE options (default)
   ```
   {
    "ansible.executionEnvironment.enabled": false,
    "ansible.executionEnvironment.image": "quay.io/ansible/ansible-navigator-demo-ee:0.6.0",
    "ansible.executionEnvironment.containerEngine": "auto",
    "ansible.executionEnvironment.pullPolicy: "missing"  
   }
   ```

 Related to ansible-langauge-server PR https://github.com/ansible/ansible-language-server/pull/42

2021-09-27 15:11 UTC, tomaciazek requested changes
Something strange happened here:
- `ansible.ansibleLint.path` got moved down without apparent reason
- `ansible.python.interpreterPath` and `ansible.python.activationScript` got thrown entirely out of `properties` and are now children of `configuration`

2021-09-28 06:57 UTC, ganeshrn commented
@tomaciazek Good catch. Last-minute unintended edit before commit messed up the order. Have fixed your review comment now. Thank you!

2021-09-28 14:11 UTC, matburt approved these changes

2021-09-29 03:34 UTC, ganeshrn commented on package.json
> +          "description": "Path to the ansible-lint executable."
Attempting to order the settings in alphabetical order, hope I got it right this time.

2021-09-29 16:50 UTC, tomaciazek approved these changes

2021-09-30 04:33 UTC, merged