Fix the line wrapping consistency in the changelog
ansible/vscode-ansible pull request #291
Opened 2021-11-01 17:05 UTC by webknjaz

2021-11-02 09:10 UTC, ssbarnea requested changes
If you really want to enforce line length limits for markdown files, please activate a linter for it.

I do not think that these kind of manual fixes are the best use of our time, especially when we do not include a preventive measure (lint)

2021-11-02 15:13 UTC, webknjaz commented
I'll look into linting when I have time. As you said, let's not waste it by blocking the merge.

2021-11-03 09:51 UTC, ssbarnea approved these changes

2021-11-03 09:52 UTC, ssbarnea commented
I do remember that one of the marketplaces had some special requirements regarding markdown. We will see if that breaks it or not and if so, we will need to add a note.

2021-11-03 09:52 UTC, merged