Remove the need to configure ansible-playbook location
ansible/vscode-ansible pull request #317
Opened 2021-11-15 16:42 UTC by ssbarnea

As ansible-playbook and all the other ansible commands are always
located alongside ansible executable itself, we have no use of
separated configuration options for them.

2021-11-15 16:44 UTC, ganeshrn approved these changes

2021-11-16 12:22 UTC, webknjaz requested changes

2021-11-16 12:22 UTC, webknjaz commented on package.json
> +          "description": "Path to the ansible executable. All subcommands are expected to located at the location."
```suggestion
          "description": "Path to the ansible executable. All subcommands are expected to have adjacent locations."
```

2021-11-16 12:22 UTC, webknjaz commented on src/features/runner.ts
> +    runExecutable += '-playbook';
Plz encapsulate this in a function.

2021-11-16 12:22 UTC, webknjaz commented on src/features/runner.ts
> -  private get ansiblePlaybookExecutablePath(): string {
Keep the property and call the helper function here instead.

2021-11-16 15:04 UTC, merged