chore: enable yamllint
ansible/vscode-ansible pull request #388
Opened 2022-01-17 18:41 UTC by ssbarnea

This enables yamllint and ensures that indentation is consistent
across our files, fixing problem where prettier would reformat the
file on save.

2022-01-17 19:06 UTC, webknjaz requested changes
Please, don't add unnecessary indents to the sequences.

2022-01-17 19:08 UTC, webknjaz commented on .yamllint
> +    indent-sequences: true
This must be
```suggestion
    indent-sequences: false
```

2022-01-17 19:19 UTC, ssbarnea commented
@webknjaz That is only imposing Ansible own standards, which is to indent sequences. In fact these files **already contained inconsistent sequences inside the same file**.

Look at PR template where labels sequence was not indented but body sequence was. Similar inside ci.yml where there was fix of the two. Basically you cannot say that is switching an indentation type with another, when in fact is consolidating it.

Before this change, editing a file in vscode would have introduced undesired indentation. At least @priyamsahoo was affected by this. In fact there are two extensions that can reformat `yaml` files when in vscode and both of them are behaving the same way (vscode-yaml and prettier).

I had a longer talk with @cidrblock today regarding which path we should take on this and some of the ideas that went out were:
* having different indentation rules based on where the yaml files are located on disk would only confuse users and force us to add a lot of complexity to our checks, shortly does not worth our time
* having ability to auto-reformat files from incoming pull-request is a valuable as almost nobody enjoys reformatting code to match a linter expectation. Having prettier auto-fix that on file save (or pre-commit) saves a lot of human time.
* we are part of Ansible team, so diverging from Ansible standards would be... not wise

Obviously that we will wait for input from the entire team on this one.

2022-01-17 19:21 UTC, webknjaz commented
I asked some time ago, among the core team members, and most preferred no indent. So no, there's no such thing as an Ansible standard.

2022-01-17 19:26 UTC, ssbarnea commented
There are serious problems especially with blocks when not using indentation. See https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html

When using blocks lack of indentation can often cause keys like `when:` to be wrongly applied to the wrong level, instead of applying to a block to apply to the last task inside the block, or the opposite. That is why very long time ago the indentation went towards always indenting sequences.

The fact that documentation uses that is not a random mistake.

2022-01-17 19:43 UTC, webknjaz commented
The documentation represents something that tech writers chose to use, that's it. There is no official guidelines from the engineering.

2022-01-17 19:51 UTC, cidrblock commented
Although I tend to not indent when making a sequence, I find both approaches legible.  Why I do appreciate is tools that ensure consistency in a repo without any manual work or intervention.

I'm a 0 on indent vs. not

+1 for a precommit something that ensures consistency

2022-01-18 05:27 UTC, priyamsahoo approved these changes
I am always in favor of consistency, irrespective of my opinion on indentations.

2022-01-18 09:15 UTC, tomaciazek commented
> Please, don't add unnecessary indents to the sequences.

Just because something is optional, does not mean that it's unnecessary. Would you write code in Java/C++/C#/JavaScript without indentation (just because curly braces are enough)? I think that indentation of sequences provides much better legibility, especially with more complex cases, such as Ansible blocks.

2022-01-18 09:16 UTC, tomaciazek approved these changes

2022-01-18 10:17 UTC, ganeshrn approved these changes

2022-01-18 12:28 UTC, cidrblock approved these changes

2022-01-18 13:40 UTC, webknjaz commented
> Just because something is optional, does not mean that it's unnecessary. Would you write code in Java/C++/C#/JavaScript without indentation (just because curly braces are enough)?

When I see an indent, I expect it to be a mapping. Sequences don't need an extra bit of syntax (both indent and a dash) — there should be one distinction, not multiple.

2022-01-18 14:13 UTC, tomaciazek commented
> > Just because something is optional, does not mean that it's unnecessary. Would you write code in Java/C++/C#/JavaScript without indentation (just because curly braces are enough)?
> 
> When I see an indent, I expect it to be a mapping. Sequences don't need an extra bit of syntax (both indent and a dash) — there should be one distinction, not multiple. Besides, too much indentation contributes to overly long lines.

Is `a` a mapping:
```yaml
- a:
  - b
  - c
```
? No. Can you skip the indent? No. Hence, you can't possibly always expect an indent to be a mapping😉

Possibility to skip indentation on *some* sequences is inconsistent in itself, to say the least. In my opinion, the fact that creators of YAML made it possible did more harm than good, causing debates such as this. Sometimes less choice is better :)

Also, the indent in case of sequences is not an extra bit of syntax - it's a bit of formatting.

2022-01-18 14:25 UTC, webknjaz commented
> ? No. Can you skip the indent? No. Hence, you can't possibly always expect an indent to be a mappingwink

But the indent is counted since the position of `a:` so there's no indent :shrug:

2022-01-18 14:27 UTC, webknjaz commented
> Sometimes less choice is better :)

Sounds like it's one step away from dictatorship. If the "no-choice" option is wrong and there's no way to fix it — is it good or bad? Let the history lessons be the answer.

2022-01-18 14:29 UTC, webknjaz commented
> Possibility to skip indentation on _some_ sequences is inconsistent in itself, to say the least.

Syntax-wise, it's not skipping in some because of the place the indentation counter starts.

2022-01-18 14:37 UTC, tomaciazek commented
> > Sometimes less choice is better :)
> 
> Sounds like it's one step away from dictatorship. If the "no-choice" option is wrong and there's no way to fix it — is it good or bad? Let the history lessons be the answer.

That got political and escalated pretty quickly :P I'm by no means in favor of dictatorship and let's drop it at that.

2022-01-18 14:47 UTC, tomaciazek commented
> > Possibility to skip indentation on _some_ sequences is inconsistent in itself, to say the least.
> 
> Syntax-wise, it's not skipping in some because of the place the indentation counter starts.

It's right in the specification: https://yaml.org/spec/1.2.2/
Just under `Example 8.21. Block Scalar Nodes`:
```
Since people perceive the “-” indicator as indentation, nested block sequences may be indented by one less space to compensate, except, of course, if nested inside another block sequence ([BLOCK-OUT context] versus [BLOCK-IN context]).
```

2022-01-18 15:05 UTC, webknjaz commented
> That got political and escalated pretty quickly :P I'm by no means in favor of dictatorship and let's drop it at that.

Blame the Godwin's Law :) The internet is filled with rubbish references of disasters of the past (it gets me every time I see people jokingly "implementing" the stalin sort, for example). Besides, everything in the world is political.
FWIW I stand by the metaphor because this is how such cases _feel_, even when applied to software — and for me, it's a way to express the degree of how strongly I feel about this (I didn't mean to imply that you may have been a dictatorship supporter, I'm sorry if this upset you).
It's one thing if people choose a tool that doesn't have options and is completely different if it's forced upon them.

As for the yamllint configuration ­— it supports an option of per-file consistency. I could live with Ansible files indented but it's hard for me to accept this in other places. One of the reasons is that some of the configs get synchronized from other repositories and having the same indentation across projects certainly helps minify the merge conflicts in diffs.

2022-01-18 15:19 UTC, tomaciazek commented
> Blame the Godwin's Law :) The internet is filled with rubbish references of disasters of the past (it gets me every time I see people jokingly "implementing" the stalin sort, for example). Besides, everything in the world is political. FWIW I stand by the metaphor because this is how such cases _feel_, even when applied to software — and for me, it's a way to express the degree of how strongly I feel about this (I didn't mean to imply that you may have been a dictatorship supporter, I'm sorry if this upset you). It's one thing if people choose a tool that doesn't have options and is completely different if it's forced upon them.
> 
> As for the yamllint configuration ­— it supports an option of per-file consistency. I could live with Ansible files indented but it's hard for me to accept this in other places. One of the reasons is that some of the configs get synchronized from other repositories and having the same indentation across projects certainly helps minify the merge conflicts in diffs.

Don't worry, I didn't get upset, nor feel offended - I just didn't want this discussion to get derailed into a political debate.

As for those synchronized config files: which ones are these? How many are there?

2022-01-18 15:40 UTC, webknjaz commented
> As for those synchronized config files: which ones are these? How many are there?

Mostly top-level configs and things under `.github/` (not only YAML) + other config-like things (e.g. the Sphinx's `conf.py` etc.). Unfortunately, this synchronization is sporadic and manual right now but I'm hoping to adopt a technique of doing a `git merge` similar to what https://github.com/jaraco/skeleton provides (Jason actually uses it on hundreds of the repos, pretty fascinating stuff), except I want it to be a bit more flexible/composable/distributed. That is when I finally get to do this (automating it on the scale is non-trivial).
There are maintenance techniques that allow reducing merge conflicts that would only benefit from similar formatting.

2022-01-18 17:51 UTC, tomaciazek commented
> Mostly top-level configs and things under `.github/` (not only YAML) + other config-like things (e.g. the Sphinx's `conf.py` etc.). Unfortunately, this synchronization is sporadic and manual right now but I'm hoping to adopt a technique of doing a `git merge` similar to what https://github.com/jaraco/skeleton provides (Jason actually uses it on hundreds of the repos, pretty fascinating stuff), except I want it to be a bit more flexible/composable/distributed. That is when I finally get to do this (automating it on the scale is non-trivial). There are maintenance techniques that allow reducing merge conflicts that would only benefit from similar formatting.

Well, that doesn't sound like that many YAML files, and I suppose the synchronization process could take care of the indentation. As for the per-file consistency, I fear that it would not improve the consistency much. Even if some less or more strict guidelines are set, more often than not we'd have PRs with change requests just because of wrong indentation, and that's just counterproductive.

2022-01-18 18:37 UTC, tomaciazek commented
Another reason for which I stopped using un-indented sequences is issues with automatic code-folding in VS Code:
![image](https://user-images.githubusercontent.com/15631478/149998024-fd911b98-86c8-4cad-8c65-5be1da31b4c4.png)

2022-01-19 03:45 UTC, ganeshrn commented
When it comes to indentation and code formatting there will always to conflicting opinions :-).
Considering the number of project maintainers we have in favour to have this PR in we do have a clear majority. I will go ahead and merge this PR. If in future we as a team collectively realise it is not the right way to go we can always revert the change.

2022-01-19 03:51 UTC, merged