Improve e2e test timings
ansible/vscode-ansible pull request #568
Opened 2022-07-26 05:53 UTC by priyamsahoo

This PR:
- decreases sleep timing between diagnostic tests.
- decreases sleep timing during re-initialization of the server.

2022-07-26 06:42 UTC, ssbarnea requested changes
Sorry but that is not the solution for our testing issue as it will generate lots of random test failures due to "only sametime slower".

The real problem is that we should have never used sleeps and test the outcome in a loop that has a timeout, that is very different than having a sleep and checking the result after the sleep.

Based on my testing, once we implement that, we should see the test running ~8-10x faster in average.

2022-08-25 02:23 UTC, priyamsahoo commented
@ssbarnea, I would suggest keeping the issue open, but for the time being, we can merge this change as this PR improves the test timings significantly, both, in local jobs and the CI jobs.

We can look at the real issue when we are free with the works with the work that we are currently doing. It is not blocking anything currenlty.

2022-08-25 08:12 UTC, ssbarnea approved these changes

2022-08-25 08:14 UTC, ssbarnea commented
> @ssbarnea, I would suggest keeping the issue open, but for the time being, we can merge this change as this PR improves the test timings significantly, both, in local jobs and the CI jobs.
> 
> We can look at the real issue when we are free with the works with the work that we are currently doing. It is not blocking anything currently.

Yep. Approved and activated auto-merge. If it happens to pass, it will get merged, if not, probably is a sign that reducing might not be best idea. Our machines are always faster than GHA, so we should be fine.

2023-10-23 05:56 UTC, closed without merging